### PR TITLE
Id::new should take &str instead of String

### PR DESCRIPTION
**Pull request by julienw**

### CODE REVIEW

**Comment by fabricedesre** [comment]
You don't want to checking src/.util.rs.swp ;)

And you need to update the macros at https://github.com/fxbox/taxonomy/blob/cd4bf669f6094b815bd47ac96e8ff243bdde0c5a/src/services.rs#L34

**Comment by julienw** [comment]
ahah I have a .gitignore with this for my own repositories ;)
OK I'll change this

**Comment by Yoric** [comment]
Thanks for the contribution :)

**Comment by fabricedesre** [comment]
hu, that was r- from me... Damn github

**Comment by julienw** [comment]
and I had done the change :p I can fire a new PR

**Comment by Yoric** [comment]
@fabricedesre Maybe we should take the habit of closing the PR if it's r-?

**Comment by fabricedesre** [comment]
And reopen once there are changes? yeah, maybe. Anyway we're moving to bugzilla :stuck_out_tongue:

**Pull request merged**
