### PR TITLE
Derive a Clone implementation for the manager

### PR DESCRIPTION
**Pull request by julienw**

### CODE REVIEW

**Comment by julienw** [comment]
Do I need a unit test @ferjm ?

**Comment by Yoric** [comment]
@julienw What's the use of this Clone implementation? All code that uses the manager now uses an `Arc<AdapterManager>`.

**Comment by julienw** [comment]
Well, it's not really needed to use another Arc to use it, right ? Because AdapterManager itself contains only Arcs...

basically my init file doesn't take a Arc but takes a &AdapterManager, and I want to clone it. It felt better. But I have no religion so I can change it.

**Comment by Yoric** [comment]
I'd rather you did the same as the other `Adapter`s (hum, as of yesterday :) ), and took an `&Arc<AdapterManager>`. It doesn't require as much knowledge of how the `AdapterManager` works, so it will let us change its behavior later if needs be.

**Comment by julienw** [comment]
With this patch I wouldn't need any knowledge, I would just need to force "+ Clone" in my where line to have the knowledge ;)

Anyway, as I said, I have no religion here. I'll change my code.

**Pull request closed without merging**
