### PR TITLE
Add user to fetch_values and send_values. r=Yoric

### LINKED ISSUE #246: Transmit user identification from http to the services
The webpush adapter/service is hardcoding its user id because right now we don't surface the current authenticated user from the http layer to the getters and setters. Let's add that.

### PR DESCRIPTION
**Pull request by ferjm**
This is required to fix https://github.com/fxbox/foxbox/issues/246

### CODE REVIEW

**Comment by Yoric** [comment]
@ferjm Can you make sure that this won't break Thinkerbell?

**Comment by ferjm** [comment]
Yes, I need to update Thinkerbell to the latest taxonomy rev first.

**Comment by Yoric** [comment]
@ferjm Adding label "Not ready" just to make double-plus sure nobody merges this by accident. Remove the label when you are ready.

**Comment by ferjm** [comment]
I think this is ready for review. @Yoric, do you mind taking a look, please? Thanks!

**Comment by Yoric** [comment]
r=me

**Comment by Yoric** [comment]
I'll let you merge when you're ready.

**Pull request merged**
