### PR TITLE
Issue #21 - Implement ToString for Id

### PR DESCRIPTION
**Pull request by hfiguiere**
Is that what you meant? I use the standard trait ToString.

@yoric r?

### CODE REVIEW

**Comment by Yoric** [comment]
Looks good to me. Could you add a doctest, while you're at it?

**Comment by hfiguiere** [comment]
Good idea.

**Comment by hfiguiere** [comment]
Good idea. Done. @yoric r? (I don't have merge privileges either)

**Comment by Yoric** [comment]
Thanks for the patch!

**Pull request merged**
